Repository ctoec/ecis-experimental, pull requests merged in 2020-02, with the labels that each got.

#746 publish test on success or failure (#745)
  azure-pipelines.yml
Labels: devops

#787 Multi site roster view
  src/Hedwig/ClientApp/src/components/Button/Button.tsx
  src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDropdown.module.scss
  src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDrowdown.tsx
  src/Hedwig/ClientApp/src/containers/App/App.tsx
  src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap
  src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx
  src/Hedwig/ClientApp/src/containers/Roster/Roster.test.tsx
  src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx
  src/Hedwig/ClientApp/src/containers/Roster/RosterHeader.tsx
  src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
  src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts
  src/Hedwig/ClientApp/src/hooks/useHideOnLostFocus.ts
  src/Hedwig/ClientApp/src/index.tsx
  src/Hedwig/ClientApp/src/tests/data/organization.ts
  src/Hedwig/Repositories/OrganizationRepository.cs
  src/Hedwig/Repositories/SiteRepository.cs
Labels: pull request environment

#800 Add an enroll button for multisite program roster
  src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDropdown.module.scss
  src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDrowdown.tsx
  src/Hedwig/ClientApp/src/components/InlineIcon/InlineIcon.tsx
  src/Hedwig/ClientApp/src/containers/Roster/RosterHeader.tsx
Labels: pull request environment

#813 increase pr system disk size (#812)
  installer/tf/prsystem/main.tf
  installer/tf/prsystem/startup.sh
Labels: devops, pull request environment
